# -*- coding: utf-8 -*-
"""H_GTT_45day_Lookback.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjsAgiS24V_QaacOB-ixeAVPQgPiY2tq
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install torch-geometric -q
!pip install torch==2.5.0 -q

!pip install xgboost lightgbm statsmodels -q

"""# ============================================================
# H-GTT Solar Forecasting – 45-day Lookback, 1-day Forecast
# STEP 1: Data loading, sequence creation, splits, API stub
# ============================================================
"""

import io
import numpy as np
import pandas as pd
import requests
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from torch_geometric.nn import GATConv, TransformerConv

"""# ============================================================
# API details (same as your original, but use dates in paper)
# ============================================================
"""

API_KEY = "2JJJR627HH6EN43LY65K29KYS"
LOCATION = "PAVAGADA"
API_URL = (
    "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/"
    f"timeline/{LOCATION}?unitGroup=metric&elements=datetime,temp,humidity,"
    "windspeed,cloudcover,solarradiation&include=days&key="
    f"{API_KEY}&contentType=csv"
)

class HybridGTT(nn.Module):
    def __init__(self, in_features, gat_hidden_dim, transformer_hidden_dim, heads=4):
        super(HybridGTT, self).__init__()
        # GAT stack
        self.gat1 = GATConv(in_features, gat_hidden_dim, heads=heads)
        self.gat2 = GATConv(gat_hidden_dim * heads, gat_hidden_dim, heads=1)

        # TransformerConv stack
        self.trans1 = TransformerConv(gat_hidden_dim, transformer_hidden_dim)
        self.trans2 = TransformerConv(transformer_hidden_dim, transformer_hidden_dim)

        self.fc = nn.Linear(transformer_hidden_dim, 1)
        self.reset_parameters()

    def reset_parameters(self):
        self.gat1.reset_parameters()
        self.gat2.reset_parameters()
        self.trans1.reset_parameters()
        self.trans2.reset_parameters()
        nn.init.xavier_uniform_(self.fc.weight)
        nn.init.zeros_(self.fc.bias)

    def forward(self, x, edge_index):
        x = F.relu(self.gat1(x, edge_index))
        x = F.relu(self.gat2(x, edge_index))
        x = F.relu(self.trans1(x, edge_index))
        x = F.relu(self.trans2(x, edge_index))
        return self.fc(x)


class GATOnly(nn.Module):
    """Ablation: GAT + FC, no TransformerConv."""
    def __init__(self, in_features, gat_hidden_dim=64, heads=4):
        super().__init__()
        self.gat = GATConv(in_features, gat_hidden_dim, heads=heads)
        self.fc = nn.Linear(gat_hidden_dim * heads, 1)
        self.reset_parameters()

    def reset_parameters(self):
        self.gat.reset_parameters()
        nn.init.xavier_uniform_(self.fc.weight)
        nn.init.zeros_(self.fc.bias)

    def forward(self, x, edge_index):
        x = F.relu(self.gat(x, edge_index))
        return self.fc(x)


class TransformerOnly(nn.Module):
    """Ablation: TransformerConv + FC, no GAT."""
    def __init__(self, in_features, hidden_dim=64):
        super().__init__()
        self.transformer = TransformerConv(in_features, hidden_dim)
        self.fc = nn.Linear(hidden_dim, 1)
        self.reset_parameters()

    def reset_parameters(self):
        self.transformer.reset_parameters()
        nn.init.xavier_uniform_(self.fc.weight)
        nn.init.zeros_(self.fc.bias)

    def forward(self, x, edge_index):
        x = F.relu(self.transformer(x, edge_index))
        return self.fc(x)

def load_data(file_path):
    df = pd.read_csv(file_path)

    features = df[['temp', 'humidity', 'windspeed', 'cloudcover', 'solarradiation']].values.astype(np.float32)
    target = df['solarenergy(GWh)'].values.astype(np.float32)

    n = len(df)
    train_end = int(0.8 * n)   # 80% for train+val, 20% for test

    # Raw splits (no scaling yet)
    X_trainval_raw = features[:train_end]
    y_trainval_raw = target[:train_end]
    X_test_raw = features[train_end:]
    y_test_raw = target[train_end:]

    # Scale features on TRAIN+VAL only
    scaler = StandardScaler()
    X_trainval = scaler.fit_transform(X_trainval_raw)
    X_test = scaler.transform(X_test_raw)

    # Normalize target on TRAIN+VAL only
    target_mean = y_trainval_raw.mean()
    target_std = y_trainval_raw.std() if y_trainval_raw.std() > 0 else 1.0
    y_trainval = (y_trainval_raw - target_mean) / target_std
    y_test = (y_test_raw - target_mean) / target_std

    # Validation = last 20% of trainval
    n_trainval = len(X_trainval)
    val_size = int(0.2 * n_trainval)
    if val_size < 10:
        val_size = max(10, n_trainval // 5)

    X_train = X_trainval[:-val_size]
    y_train = y_trainval[:-val_size]
    X_val = X_trainval[-val_size:]
    y_val = y_trainval[-val_size:]

    # To tensors
    X_train = torch.tensor(X_train, dtype=torch.float32)
    X_val = torch.tensor(X_val, dtype=torch.float32)
    X_test = torch.tensor(X_test, dtype=torch.float32)
    y_train = torch.tensor(y_train, dtype=torch.float32)
    y_val = torch.tensor(y_val, dtype=torch.float32)
    y_test = torch.tensor(y_test, dtype=torch.float32)

    def make_edge_index(length):
        if length < 2:
            return torch.zeros((2, 0), dtype=torch.long)
        return torch.tensor(
            [[i, i + 1] for i in range(length - 1)],
            dtype=torch.long
        ).t().contiguous()

    edge_index_train = make_edge_index(len(X_train))
    edge_index_val = make_edge_index(len(X_val))
    edge_index_test = make_edge_index(len(X_test))

    return (X_train, y_train, edge_index_train,
            X_val, y_val, edge_index_val,
            X_test, y_test, edge_index_test,
            target_mean, target_std, scaler,
            y_trainval_raw, y_test_raw)

# =========================
# EXTRA IMPORTS FOR BASELINES
# =========================
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from statsmodels.tsa.arima.model import ARIMA

# =========================
# LSTM BASELINE
# =========================
class LSTMBaseline(nn.Module):
    def __init__(self, in_features, hidden_size=64, num_layers=2):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=in_features,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True
        )
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x_seq):
        """
        x_seq: (batch, seq_len, in_features)
        """
        out, _ = self.lstm(x_seq)
        last_out = out[:, -1, :]  # last time step
        return self.fc(last_out)


# =========================
# HELPER: LAG FEATURES FOR XGBOOST / LIGHTGBM
# =========================
def create_lag_features(X, y, lags=[1, 2, 3, 7]):
    """
    X: numpy array (N, num_features)
    y: numpy array (N,)
    Returns: X_lagged, y_lagged
    """
    X_lags = []
    y_lags = []
    max_lag = max(lags)
    for i in range(max_lag, len(X)):
        row = []
        for lag in lags:
            row.extend(X[i - lag])
        X_lags.append(row)
        y_lags.append(y[i])
    return np.array(X_lags), np.array(y_lags)


# =========================
# LSTM TRAIN FUNCTION
# =========================
def train_lstm_baseline(X_train, y_train, X_val, y_val,
                        X_test, y_test,
                        target_mean, target_std,
                        num_epochs=100, patience=20, lr=0.001):
    """
    X_*: torch tensors, shape (N, num_features) - SAME as from load_data
    y_*: torch tensors, normalized
    """
    # reshape to (N, seq_len=1, features)
    X_train_seq = X_train.unsqueeze(1)
    X_val_seq   = X_val.unsqueeze(1)
    X_test_seq  = X_test.unsqueeze(1)

    model = LSTMBaseline(in_features=X_train.shape[1], hidden_size=64, num_layers=2)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = torch.nn.MSELoss()

    best_val_mae = float('inf')
    best_state = None
    patience_counter = 0

    for epoch in range(1, num_epochs + 1):
        model.train()
        optimizer.zero_grad()
        train_pred = model(X_train_seq).squeeze()
        train_loss = criterion(train_pred, y_train)
        train_loss.backward()
        optimizer.step()

        train_mae = mean_absolute_error(
            y_train.detach().cpu().numpy(),
            train_pred.detach().cpu().numpy()
        )

        model.eval()
        with torch.no_grad():
            val_pred = model(X_val_seq).squeeze()
            val_loss = criterion(val_pred, y_val).item()
            val_mae = mean_absolute_error(
                y_val.detach().cpu().numpy(),
                val_pred.detach().cpu().numpy()
            )

        if epoch == 1 or epoch % 10 == 0:
            print(f"[LSTM] Epoch {epoch:03d} | "
                  f"Train Loss={train_loss.item():.4f} MAE={train_mae:.4f} | "
                  f"Val Loss={val_loss:.4f} MAE={val_mae:.4f}")

        if val_mae < best_val_mae:
            best_val_mae = val_mae
            best_state = model.state_dict()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"[LSTM] Early stopping at epoch {epoch}")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    # Test evaluation (de-normalize)
    model.eval()
    with torch.no_grad():
        y_pred_test_norm = model(X_test_seq).squeeze().cpu().numpy()
        y_true_test_norm = y_test.cpu().numpy()

    y_pred_test = y_pred_test_norm * target_std + target_mean
    y_true_test = y_true_test_norm * target_std + target_mean

    mae = mean_absolute_error(y_true_test, y_pred_test)
    rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    r2 = r2_score(y_true_test, y_pred_test)

    print("\n=== FINAL TEST PERFORMANCE (LSTM) ===")
    print(f"MAE (GWh): {mae:.4f}")
    print(f"RMSE (GWh): {rmse:.4f}")
    print(f"R²: {r2:.4f}")

    return mae, rmse, r2


# =========================
# XGBOOST BASELINE
# =========================
def train_xgboost_baseline(X_trainval_raw, y_trainval_raw,
                           X_test_raw, y_test_raw):
    """
    *_raw: numpy arrays in ORIGINAL scale (not normalized).
    Use the SAME temporal split as your main model:
    - trainval = first 80%
    - test     = last 20%
    """
    # Build lag features on trainval and test separately
    X_train_lags, y_train_lags = create_lag_features(X_trainval_raw, y_trainval_raw)
    X_test_lags, y_test_lags   = create_lag_features(X_test_raw, y_test_raw)

    # Standardize lag features
    scaler = StandardScaler()
    X_train_lags = scaler.fit_transform(X_train_lags)
    X_test_lags  = scaler.transform(X_test_lags)

    model = XGBRegressor(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        random_state=42
    )
    model.fit(X_train_lags, y_train_lags)

    y_pred = model.predict(X_test_lags)

    mae = mean_absolute_error(y_test_lags, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test_lags, y_pred))
    r2 = r2_score(y_test_lags, y_pred)

    print("\n=== XGBoost Baseline ===")
    print(f"MAE (GWh): {mae:.4f}")
    print(f"RMSE (GWh): {rmse:.4f}")
    print(f"R²: {r2:.4f}")

    return mae, rmse, r2


# =========================
# LIGHTGBM BASELINE
# =========================
def train_lightgbm_baseline(X_trainval_raw, y_trainval_raw,
                            X_test_raw, y_test_raw):
    X_train_lags, y_train_lags = create_lag_features(X_trainval_raw, y_trainval_raw)
    X_test_lags, y_test_lags   = create_lag_features(X_test_raw, y_test_raw)

    scaler = StandardScaler()
    X_train_lags = scaler.fit_transform(X_train_lags)
    X_test_lags  = scaler.transform(X_test_lags)

    model = LGBMRegressor(
        n_estimators=200,
        max_depth=-1,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    )
    model.fit(X_train_lags, y_train_lags)

    y_pred = model.predict(X_test_lags)

    mae = mean_absolute_error(y_test_lags, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test_lags, y_pred))
    r2 = r2_score(y_test_lags, y_pred)

    print("\n=== LightGBM Baseline ===")
    print(f"MAE (GWh): {mae:.4f}")
    print(f"RMSE (GWh): {rmse:.4f}")
    print(f"R²: {r2:.4f}")

    return mae, rmse, r2


# =========================
# ARIMA BASELINE
# =========================
def train_arima_baseline(y_trainval_raw, y_test_raw):
    """
    Simple ARIMA(1,1,1) on raw target.
    Train on trainval, forecast len(test) steps.
    """
    model = ARIMA(y_trainval_raw, order=(1, 1, 1))
    result = model.fit()

    forecast = result.get_forecast(steps=len(y_test_raw)).predicted_mean

    y_pred = np.array(forecast)
    y_true = np.array(y_test_raw)

    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    print("\n=== ARIMA(1,1,1) Baseline ===")
    print(f"MAE (GWh): {mae:.4f}")
    print(f"RMSE (GWh): {rmse:.4f}")
    print(f"R²: {r2:.4f}")

    return mae, rmse, r2


# =========================
# TRANSFORMER BASELINE
# =========================
class TransformerBaseline(nn.Module):
    def __init__(self, in_features, d_model=64, nhead=4, num_layers=2):
        super().__init__()
        self.input_proj = nn.Linear(in_features, d_model)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=256,
            batch_first=True
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.fc = nn.Linear(d_model, 1)

    def forward(self, x_seq):
        """
        x_seq: (batch, seq_len, in_features)
        """
        x = self.input_proj(x_seq)
        out = self.encoder(x)
        last_out = out[:, -1, :]
        return self.fc(last_out)


def train_transformer_baseline(X_train, y_train, X_val, y_val,
                               X_test, y_test,
                               target_mean, target_std,
                               num_epochs=100, patience=20, lr=0.001):
    X_train_seq = X_train.unsqueeze(1)
    X_val_seq   = X_val.unsqueeze(1)
    X_test_seq  = X_test.unsqueeze(1)

    model = TransformerBaseline(in_features=X_train.shape[1])
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = torch.nn.MSELoss()

    best_val_mae = float('inf')
    best_state = None
    patience_counter = 0

    for epoch in range(1, num_epochs + 1):
        model.train()
        optimizer.zero_grad()
        train_pred = model(X_train_seq).squeeze()
        train_loss = criterion(train_pred, y_train)
        train_loss.backward()
        optimizer.step()

        train_mae = mean_absolute_error(
            y_train.detach().cpu().numpy(),
            train_pred.detach().cpu().numpy()
        )

        model.eval()
        with torch.no_grad():
            val_pred = model(X_val_seq).squeeze()
            val_loss = criterion(val_pred, y_val).item()
            val_mae = mean_absolute_error(
                y_val.detach().cpu().numpy(),
                val_pred.detach().cpu().numpy()
            )

        if epoch == 1 or epoch % 10 == 0:
            print(f"[Transformer] Epoch {epoch:03d} | "
                  f"Train Loss={train_loss.item():.4f} MAE={train_mae:.4f} | "
                  f"Val Loss={val_loss:.4f} MAE={val_mae:.4f}")

        if val_mae < best_val_mae:
            best_val_mae = val_mae
            best_state = model.state_dict()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"[Transformer] Early stopping at epoch {epoch}")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    model.eval()
    with torch.no_grad():
        y_pred_test_norm = model(X_test_seq).squeeze().cpu().numpy()
        y_true_test_norm = y_test.cpu().numpy()

    y_pred_test = y_pred_test_norm * target_std + target_mean
    y_true_test = y_true_test_norm * target_std + target_mean

    mae = mean_absolute_error(y_true_test, y_pred_test)
    rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    r2 = r2_score(y_true_test, y_pred_test)

    print("\n=== FINAL TEST PERFORMANCE (Transformer Baseline) ===")
    print(f"MAE (GWh): {mae:.4f}")
    print(f"RMSE (GWh): {rmse:.4f}")
    print(f"R²: {r2:.4f}")

    return mae, rmse, r2

def train_hybridgtt(data_path, num_epochs=300, patience=25, lr=0.001):
    (X_train, y_train, edge_index_train,
     X_val, y_val, edge_index_val,
     X_test, y_test, edge_index_test,
     target_mean, target_std, scaler,
     y_trainval_raw, y_test_raw) = load_data(data_path)

    model = HybridGTT(in_features=X_train.shape[1],
                      gat_hidden_dim=160,
                      transformer_hidden_dim=96)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = torch.nn.MSELoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=5, verbose=False
    )

    best_val_mae = float('inf')
    best_state = None
    patience_counter = 0

    for epoch in range(1, num_epochs + 1):
        # ---- TRAIN ----
        model.train()
        optimizer.zero_grad()
        train_pred = model(X_train, edge_index_train).squeeze()
        train_loss = criterion(train_pred, y_train)
        train_loss.backward()
        optimizer.step()

        train_mae = mean_absolute_error(
            y_train.detach().cpu().numpy(),
            train_pred.detach().cpu().numpy()
        )

        # ---- VAL ----
        model.eval()
        with torch.no_grad():
            if len(X_val) > 1:
                val_pred = model(X_val, edge_index_val).squeeze()
                val_loss = criterion(val_pred, y_val).item()
                val_mae = mean_absolute_error(
                    y_val.detach().cpu().numpy(),
                    val_pred.detach().cpu().numpy()
                )
            else:
                val_loss = float('nan')
                val_mae = float('nan')

        scheduler_loss = torch.tensor(val_loss if not np.isnan(val_loss) else train_loss.item())
        scheduler.step(scheduler_loss)

        if epoch == 1 or epoch % 10 == 0:
            print(f"[HybridGTT] Epoch {epoch:03d} | "
                  f"Train Loss={train_loss.item():.4f} MAE={train_mae:.4f} | "
                  f"Val Loss={val_loss:.4f} MAE={val_mae:.4f}")

        # Early stopping on val MAE
        if not np.isnan(val_mae) and val_mae < best_val_mae:
            best_val_mae = val_mae
            best_state = model.state_dict()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"[HybridGTT] Early stopping at epoch {epoch}")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    # ---- TEST EVAL ----
    model.eval()
    with torch.no_grad():
        y_pred_test_norm = model(X_test, edge_index_test).squeeze().cpu().numpy()
        y_true_test_norm = y_test.cpu().numpy()

    y_pred_test = y_pred_test_norm * target_std + target_mean
    y_true_test = y_true_test_norm * target_std + target_mean

    test_mae = mean_absolute_error(y_true_test, y_pred_test)
    test_rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    test_r2 = r2_score(y_true_test, y_pred_test)

    print("\n=== FINAL TEST PERFORMANCE (HybridGTT) ===")
    print(f"MAE (GWh):  {test_mae:.4f}")
    print(f"RMSE (GWh): {test_rmse:.4f}")
    print(f"R²:         {test_r2:.4f}")

    return model, (X_test, edge_index_test, target_mean, target_std, scaler,
               y_trainval_raw, y_test_raw, test_mae, test_rmse, test_r2)

def train_and_eval_generic(model_class, model_name, data_path,
                           num_epochs=300, patience=25, lr=0.001):
    (X_train, y_train, edge_index_train,
     X_val, y_val, edge_index_val,
     X_test, y_test, edge_index_test,
     target_mean, target_std, scaler,
     y_trainval_raw, y_test_raw) = load_data(data_path)

    model = model_class(in_features=X_train.shape[1])
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = torch.nn.MSELoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=5, verbose=False
    )

    best_val_mae = float('inf')
    best_state = None
    patience_counter = 0

    for epoch in range(1, num_epochs + 1):
        model.train()
        optimizer.zero_grad()
        train_pred = model(X_train, edge_index_train).squeeze()
        train_loss = criterion(train_pred, y_train)
        train_loss.backward()
        optimizer.step()

        train_mae = mean_absolute_error(
            y_train.detach().cpu().numpy(),
            train_pred.detach().cpu().numpy()
        )

        model.eval()
        with torch.no_grad():
            if len(X_val) > 1:
                val_pred = model(X_val, edge_index_val).squeeze()
                val_loss = criterion(val_pred, y_val).item()
                val_mae = mean_absolute_error(
                    y_val.detach().cpu().numpy(),
                    val_pred.detach().cpu().numpy()
                )
            else:
                val_loss = float('nan')
                val_mae = float('nan')

        scheduler_loss = torch.tensor(val_loss if not np.isnan(val_loss) else train_loss.item())
        scheduler.step(scheduler_loss)

        if epoch == 1 or epoch % 10 == 0:
            print(f"[{model_name}] Epoch {epoch:03d} | "
                  f"Train Loss={train_loss.item():.4f} MAE={train_mae:.4f} | "
                  f"Val Loss={val_loss:.4f} MAE={val_mae:.4f}")

        if not np.isnan(val_mae) and val_mae < best_val_mae:
            best_val_mae = val_mae
            best_state = model.state_dict()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"[{model_name}] Early stopping at epoch {epoch}")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    model.eval()
    with torch.no_grad():
        y_pred_test_norm = model(X_test, edge_index_test).squeeze().cpu().numpy()
        y_true_test_norm = y_test.cpu().numpy()

    y_pred_test = y_pred_test_norm * target_std + target_mean
    y_true_test = y_true_test_norm * target_std + target_mean

    test_mae = mean_absolute_error(y_true_test, y_pred_test)
    test_rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    test_r2 = r2_score(y_true_test, y_pred_test)

    print(f"\n=== FINAL TEST PERFORMANCE ({model_name}) ===")
    print(f"MAE (GWh):  {test_mae:.4f}")
    print(f"RMSE (GWh): {test_rmse:.4f}")
    print(f"R²:         {test_r2:.4f}")

    return test_mae, test_rmse, test_r2

def persistence_baseline(y_train_raw, y_test_raw):
    y_train_raw = np.asarray(y_train_raw)
    y_test_raw = np.asarray(y_test_raw)

    preds = []
    last_val = y_train_raw[-1]
    for t in range(len(y_test_raw)):
        preds.append(last_val)
        last_val = y_test_raw[t]

    preds = np.array(preds)
    mae = mean_absolute_error(y_test_raw, preds)
    rmse = np.sqrt(mean_squared_error(y_test_raw, preds))
    r2 = r2_score(y_test_raw, preds)

    print("\n=== Persistence Baseline ===")
    print(f"MAE (GWh):  {mae:.4f}")
    print(f"RMSE (GWh): {rmse:.4f}")
    print(f"R²:         {r2:.4f}")
    return mae, rmse, r2


def mean_baseline(y_train_raw, y_test_raw):
    y_train_raw = np.asarray(y_train_raw)
    y_test_raw = np.asarray(y_test_raw)

    mean_val = y_train_raw.mean()
    preds = np.full_like(y_test_raw, fill_value=mean_val, dtype=np.float32)

    mae = mean_absolute_error(y_test_raw, preds)
    rmse = np.sqrt(mean_squared_error(y_test_raw, preds))
    r2 = r2_score(y_test_raw, preds)

    print("\n=== Mean Baseline ===")
    print(f"MAE (GWh):  {mae:.4f}")
    print(f"RMSE (GWh): {rmse:.4f}")
    print(f"R²:         {r2:.4f}")
    return mae, rmse, r2

def fetch_weather_data(api_url):
    response = requests.get(api_url)
    if response.status_code != 200:
        raise ValueError(f"Failed to fetch weather data. Response Code: {response.status_code}")

    df = pd.read_csv(io.StringIO(response.text))
    df = df[['temp', 'humidity', 'windspeed', 'cloudcover', 'solarradiation']]
    df = df.apply(pd.to_numeric, errors='coerce').dropna()

    if df.shape[0] < 5:
        raise ValueError(f"Insufficient data rows after cleaning. Found {df.shape[0]} rows.")

    return df[:5]


def predict_next_5_days(model, scaler, api_url, target_mean, target_std):
    raw_data = fetch_weather_data(api_url)
    scaled_data = torch.tensor(scaler.transform(raw_data), dtype=torch.float32)

    num_nodes = scaled_data.shape[0]
    if num_nodes < 2:
        raise ValueError("Need at least 2 rows for a time-chain graph.")

    edge_index = torch.tensor(
        [[i, i + 1] for i in range(num_nodes - 1)],
        dtype=torch.long
    ).t().contiguous()

    with torch.no_grad():
        predictions_norm = model(scaled_data, edge_index).squeeze().numpy()

    predictions = predictions_norm * target_std + target_mean
    return predictions

"""## MAIN"""

if __name__ == "__main__":
    data_path = "/content/drive/My Drive/SOLAR ENERGY FORECASTING PROJECT/solar_data.csv"

    # ----------------------------------------------------
    # 1) Load data once (same as train_hybridgtt uses)
    # ----------------------------------------------------
    (X_train, y_train, edge_index_train,
     X_val, y_val, edge_index_val,
     X_test, y_test, edge_index_test,
     target_mean, target_std, scaler,
     y_trainval_raw, y_test_raw) = load_data(data_path)

    # ----------------------------------------------------
    # 2) H-GTT (main model)
    # ----------------------------------------------------
    model, (X_test2, edge_index_test2, target_mean2, target_std2, scaler2,
        y_trainval_raw2, y_test_raw2, hgtt_mae, hgtt_rmse, hgtt_r2) = train_hybridgtt(data_path)



    # ----------------------------------------------------
    # 3) Simple baselines (already had these)
    # ----------------------------------------------------
    persistence_mae, persistence_rmse, persistence_r2 = persistence_baseline(
        y_trainval_raw, y_test_raw
    )
    mean_mae, mean_rmse, mean_r2 = mean_baseline(
        y_trainval_raw, y_test_raw
    )

    # ----------------------------------------------------
    # 4) Ablations (already had these)
    # ----------------------------------------------------
    gat_mae, gat_rmse, gat_r2 = train_and_eval_generic(GATOnly, "GAT-Only", data_path)
    transf_mae, transf_rmse, transf_r2 = train_and_eval_generic(TransformerOnly, "Transformer-Only", data_path)

    # ----------------------------------------------------
    # 5) New deep baselines: LSTM, Transformer
    # ----------------------------------------------------
    lstm_mae, lstm_rmse, lstm_r2 = train_lstm_baseline(
        X_train, y_train, X_val, y_val, X_test, y_test,
        target_mean, target_std
    )

    transformer_mae, transformer_rmse, transformer_r2 = train_transformer_baseline(
        X_train, y_train, X_val, y_val, X_test, y_test,
        target_mean, target_std
    )

    # ----------------------------------------------------
    # 6) XGBoost, LightGBM, ARIMA (use raw arrays)
    # ----------------------------------------------------
    df = pd.read_csv(data_path)
    features_raw = df[['temp', 'humidity', 'windspeed', 'cloudcover', 'solarradiation']].values.astype(np.float32)
    target_raw   = df['solarenergy(GWh)'].values.astype(np.float32)

    n = len(df)
    train_end = int(0.8 * n)

    X_trainval_raw = features_raw[:train_end]
    y_trainval_raw_full = target_raw[:train_end]
    X_test_raw = features_raw[train_end:]
    y_test_raw_full = target_raw[train_end:]

    xgb_mae, xgb_rmse, xgb_r2 = train_xgboost_baseline(
        X_trainval_raw, y_trainval_raw_full,
        X_test_raw, y_test_raw_full
    )

    lgbm_mae, lgbm_rmse, lgbm_r2 = train_lightgbm_baseline(
        X_trainval_raw, y_trainval_raw_full,
        X_test_raw, y_test_raw_full
    )

    arima_mae, arima_rmse, arima_r2 = train_arima_baseline(
        y_trainval_raw_full, y_test_raw_full
    )

    # ----------------------------------------------------
    # 7) Print a summary table for the paper
    # ----------------------------------------------------
    print("\n=== SUMMARY TABLE (for paper) ===")
    print(f"{'Model':20s} | {'MAE':>10s} | {'RMSE':>10s} | {'R²':>8s}")
    print("-" * 60)
    print(f"{'H-GTT':20s}        | {hgtt_mae:10.2f} | {hgtt_rmse:10.2f} | {hgtt_r2:8.4f}")
    print(f"{'LSTM':20s}          | {lstm_mae:10.2f} | {lstm_rmse:10.2f} | {lstm_r2:8.4f}")
    print(f"{'Transformer':20s}    | {transformer_mae:10.2f} | {transformer_rmse:10.2f} | {transformer_r2:8.4f}")
    print(f"{'XGBoost':20s}        | {xgb_mae:10.2f} | {xgb_rmse:10.2f} | {xgb_r2:8.4f}")
    print(f"{'LightGBM':20s}       | {lgbm_mae:10.2f} | {lgbm_rmse:10.2f} | {lgbm_r2:8.4f}")
    print(f"{'ARIMA':20s}          | {arima_mae:10.2f} | {arima_rmse:10.2f} | {arima_r2:8.4f}")
    print(f"{'Persistence':20s}    | {persistence_mae:10.2f} | {persistence_rmse:10.2f} | {persistence_r2:8.4f}")
    print(f"{'Mean':20s}           | {mean_mae:10.2f} | {mean_rmse:10.2f} | {mean_r2:8.4f}")
    print(f"{'GAT-Only':20s}       | {gat_mae:10.2f} | {gat_rmse:10.2f} | {gat_r2:8.4f}")
    print(f"{'Transformer-Only':20s} | {transf_mae:10.2f} | {transf_rmse:10.2f} | {transf_r2:8.4f}")

"""### GRAPHS AND PLOTS"""

def train_hybridgtt(data_path, num_epochs=300, patience=25, lr=0.001):
    (X_train, y_train, edge_index_train,
     X_val, y_val, edge_index_val,
     X_test, y_test, edge_index_test,
     target_mean, target_std, scaler,
     y_trainval_raw, y_test_raw) = load_data(data_path)

    model = HybridGTT(in_features=X_train.shape[1],
                      gat_hidden_dim=160,
                      transformer_hidden_dim=80)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = torch.nn.MSELoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=5, verbose=False
    )

    best_val_mae = float('inf')
    best_state = None
    patience_counter = 0

    # history dict to record training progress
    history = {
        "train_loss": [],
        "train_mae": [],
        "val_loss": [],
        "val_mae": []
    }

    for epoch in range(1, num_epochs + 1):
        # ---- TRAIN ----
        model.train()
        optimizer.zero_grad()
        train_pred = model(X_train, edge_index_train).squeeze()
        train_loss = criterion(train_pred, y_train)
        train_loss.backward()
        optimizer.step()

        train_mae = mean_absolute_error(
            y_train.detach().cpu().numpy(),
            train_pred.detach().cpu().numpy()
        )

        # ---- VAL ----
        model.eval()
        with torch.no_grad():
            if len(X_val) > 1:
                val_pred = model(X_val, edge_index_val).squeeze()
                val_loss = criterion(val_pred, y_val).item()
                val_mae = mean_absolute_error(
                    y_val.detach().cpu().numpy(),
                    val_pred.detach().cpu().numpy()
                )
            else:
                val_loss = float('nan')
                val_mae = float('nan')

        scheduler_loss = torch.tensor(val_loss if not np.isnan(val_loss) else train_loss.item())
        scheduler.step(scheduler_loss)

        # store in history
        history["train_loss"].append(train_loss.item())
        history["train_mae"].append(train_mae)
        history["val_loss"].append(val_loss)
        history["val_mae"].append(val_mae)

        if epoch == 1 or epoch % 10 == 0:
            print(f"[HybridGTT] Epoch {epoch:03d} | "
                  f"Train Loss={train_loss.item():.4f} MAE={train_mae:.4f} | "
                  f"Val Loss={val_loss:.4f} MAE={val_mae:.4f}")

        # Early stopping on val MAE
        if not np.isnan(val_mae) and val_mae < best_val_mae:
            best_val_mae = val_mae
            best_state = model.state_dict()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"[HybridGTT] Early stopping at epoch {epoch}")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    # ---- TEST EVAL ----
    model.eval()
    with torch.no_grad():
        y_pred_test_norm = model(X_test, edge_index_test).squeeze().cpu().numpy()
        y_true_test_norm = y_test.cpu().numpy()

    y_pred_test = y_pred_test_norm * target_std + target_mean
    y_true_test = y_true_test_norm * target_std + target_mean

    test_mae = mean_absolute_error(y_true_test, y_pred_test)
    test_rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    test_r2 = r2_score(y_true_test, y_pred_test)

    print("\n=== FINAL TEST PERFORMANCE (HybridGTT) ===")
    print(f"MAE (GWh):  {test_mae:.4f}")
    print(f"RMSE (GWh): {test_rmse:.4f}")
    print(f"R²:         {test_r2:.4f}")

    return model, (X_test, edge_index_test, target_mean, target_std, scaler,
                   y_trainval_raw, y_test_raw, y_true_test, y_pred_test, history)

import matplotlib.pyplot as plt

def plot_training_curves(history):
    epochs = range(1, len(history["train_loss"]) + 1)

    plt.figure(figsize=(10, 4))

    # Loss
    plt.subplot(1, 2, 1)
    plt.plot(epochs, history["train_loss"], label="Train Loss")
    plt.plot(epochs, history["val_loss"], label="Val Loss")
    plt.xlabel("Epoch")
    plt.ylabel("MSE Loss")
    plt.title("HybridGTT Training & Validation Loss")
    plt.grid(True)
    plt.legend()

    # MAE
    plt.subplot(1, 2, 2)
    plt.plot(epochs, history["train_mae"], label="Train MAE")
    plt.plot(epochs, history["val_mae"], label="Val MAE")
    plt.xlabel("Epoch")
    plt.ylabel("MAE (normalized)")
    plt.title("HybridGTT Training & Validation MAE")
    plt.grid(True)
    plt.legend()

    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    data_path = "/content/drive/My Drive/ENERGY FORECASTING PROJECT/solar_data.csv"

    model, (X_test, edge_index_test, target_mean, target_std, scaler,
            y_trainval_raw, y_test_raw, y_true_test, y_pred_test, history) = train_hybridgtt(data_path)

    # Plot training curves (loss & MAE vs epoch)
    plot_training_curves(history)
    ...

"""


 ### Predicted vs Actual plot (test set)
"""

import matplotlib.pyplot as plt

def plot_predicted_vs_actual(y_true, y_pred):
    """
    Line plot of actual vs predicted values over the test set.
    y_true, y_pred are 1D numpy arrays in GWh.
    """
    plt.figure(figsize=(8, 6))
    plt.plot(y_true, label='Actual', linewidth=2)
    plt.plot(y_pred, label='Predicted', linewidth=2)
    plt.title('HybridGTT: Predicted vs Actual Solar Energy (Test Set)')
    plt.xlabel('Test Sample Index')
    plt.ylabel('Solar Energy (GWh)')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    # Predicted vs Actual plot
    # y_true_test and y_pred_test are already in GWh from train_hybridgtt
    plot_predicted_vs_actual(y_true_test, y_pred_test)

"""# **Error distribution histogram**"""

def plot_error_distribution(y_true, y_pred):
    errors = y_pred - y_true
    plt.figure(figsize=(6, 4))
    plt.hist(errors, bins=30, color="skyblue", edgecolor="black")
    plt.xlabel("Prediction Error (GWh)")
    plt.ylabel("Frequency")
    plt.title("H-GTT Error Distribution")
    plt.grid(True)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
      # Error distribution histogram
    plot_error_distribution(y_true_test, y_pred_test)

"""# **Baseline and ablation summary (for tables)**"""

persistence_baseline(y_trainval_raw, y_test_raw)
    mean_baseline(y_trainval_raw, y_test_raw)

    gat_mae, gat_rmse, gat_r2 = train_and_eval_generic(GATOnly, "GAT-Only", data_path)
    transf_mae, transf_rmse, transf_r2 = train_and_eval_generic(TransformerOnly, "Transformer-Only", data_path)

    # Collect numbers for a simple comparison table (you'll copy into LaTeX/Word)
    results = {
        "HybridGTT": {
            "MAE": mean_absolute_error(y_true_test, y_pred_test),
            "RMSE": np.sqrt(mean_squared_error(y_true_test, y_pred_test)),
            "R2": r2_score(y_true_test, y_pred_test),
        },
        "GAT-Only": {
            "MAE": gat_mae, "RMSE": gat_rmse, "R2": gat_r2,
        },
        "Transformer-Only": {
            "MAE": transf_mae, "RMSE": transf_rmse, "R2": transf_r2,
        },
        # You can also record exact persistence/mean metrics by making them return values
    }

    print("\n=== SUMMARY TABLE (copy these into your paper) ===")
    for name, m in results.items():
        print(f"{name:16s} | MAE={m['MAE']:.4f} | RMSE={m['RMSE']:.4f} | R²={m['R2']:.4f}")

"""# **EPOCH TABLE**"""

def print_training_progress_table(history, epoch_points=[0, 50, 100, 150, 190]):
    """
    Print a LaTeX-style table of training/validation MAE and loss
    at selected epochs, using the 'history' dict.
    """
    max_idx = len(history["train_loss"]) - 1

    print("\n=== H-GTT Training Progress (for table) ===")
    print("Epoch | Train_MAE | Val_MAE | Train_Loss | Val_Loss")
    print("------|-----------|---------|------------|---------")
    for e in epoch_points:
        if e == 0:
            idx = 0
        else:
            idx = e - 1  # because history[0] is epoch 1
        if idx > max_idx:
            # skip epochs beyond early stopping
            continue
        t_mae = history["train_mae"][idx]
        v_mae = history["val_mae"][idx]
        t_loss = history["train_loss"][idx]
        v_loss = history["val_loss"][idx]
        print(f"{e:5d} | {t_mae:9.4f} | {v_mae:7.4f} | {t_loss:10.4f} | {v_loss:7.4f}")

if __name__ == "__main__":
    # Print training progress table values
    print_training_progress_table(history, epoch_points=[0, 50, 100, 150, 190])